### ISSUE TITLE
Does not shown warnings for badly named fields in eeg.json

### ISSUE THREAD

**Issue by sappelhoff** [robertoostenveld/bids-validator#4]
We had inconsistent usage of "manufactureR" vs. "manufacturerS" across several specifications, examples, and datasets. I have been trying to make all of that consistent with the main BIDS 1.1.1 release (using manufacturerS) ... and while doing that, I realized that the eeg-validator does check for a "manufactureR" field (which I will also change to manufacturerS in a minute) ... but does not throw a warning or error when there is a "manufacturerS" field instead.

I feel like there should be a warning such as "unexpected field encountered in eeg.json".

**Comment by robertoostenveld** [comment]
I don't know how you would want to check this: the one field is optional, so OK if missing, whereas the other field is allowed (since additional unknown fields are allowed). You would have to do some smart match that would detect that the field names are nearly similar and therefore give a warning. This is interesting, but also challenging, and not something I will implement. If you want, you could propose this at  https://github.com/INCF/bids-validator/issues

**Comment by sappelhoff** [comment]
> since additional unknown fields are allowed

Now that we are actually checking against the JSON schema (this was not the case before PR #8 ), I also realized that "additional unknown fields" are currently NOT allowed, see:

https://github.com/robertoostenveld/bids-validator/blob/56abe0062698824d9298022aa5318582460edfb8/validators/schemas/eeg.json#L55-L57

Should we keep it this way? Or change it to `true` so that "additional unknown fields" are allowed?

**Comment by robertoostenveld** [comment]
According to the written specification, additional fields (from the original DICOMs) are allowed for imaging data. There it also makes sense.  

But looking at the code I see that for MEG additional fields are not allowed. The written specification does not mention it. I propose we follow the MEG implementation and implement it strict for EEG as well (i.e. no additional fields) rather than loose. 

It is better to change it from strict to loose in the future, than the other way around.

**Comment by robertoostenveld** [comment]
since the code is now strict, the issue can be closed
